name: readthedocs
dependencies:
  - python=3.11
  - mpi4py
  - pip
  - pip:
    - -e ..
    - ax-platform >= 0.3.4
    - autodoc_pydantic >= 2.0.1
    - ipykernel
    - matplotlib
    - nbsphinx
    - numpydoc
    - pydata-sphinx-theme
    - sphinx-copybutton
    - sphinx-design
    - sphinx-gallery
    - wandb
