name: Unix

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      # Increase this value to reset cache
      env: {CACHE_NUMBER: 0}
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ matrix.python-version }}

    - uses: conda-incubator/setup-miniconda@v2
      name: Setup conda
      with:
        auto-update-conda: true
        activate-environment: testing
        auto-activate-base: false
        channels: conda-forge,defaults
        channel-priority: true

    - shell: bash -l {0}
      name: Install dependencies
      run: |
        conda install -c conda-forge python=${{ matrix.python-version }} numpy mpi4py;
        pip3 install pyflakes;
        pip3 install ax-platform;
        pip3 install git+http://github.com/Libensemble/libensemble@develop;
        pip3 install -r requirements.txt;
        python setup.py install
    - shell: bash -l {0}
      name: pyflakes
      run: python -m pyflakes libe_opt
    - shell: bash -l {0}
      name: test dummy example
      run: |
        cd optimization_folder;
        ./create_new_optimization.py --name test --from dummy --machine local --n_sim_workers 2;
        cd test; python run_example.py --comms local --nworkers 3
    - shell: bash -l {0}
      name: test dummy_mf example
      run: |
        cd optimization_folder;
        ./create_new_optimization.py --name test_mf --from dummy_mf --machine local --n_sim_workers 2;
        cd test_mf; python run_example.py --comms local --nworkers 3
    - shell: bash -l {0}
      name: test dummy_mf_disc example
      run: |
        cd optimization_folder;
        ./create_new_optimization.py --name test_mf_disc --from dummy_mf_disc --machine local --n_sim_workers 2;
        cd test_mf_disc; python run_example.py --comms local --nworkers 3
    - shell: bash -l {0}
      name: test dummy_ax example
      run: |
        cd optimization_folder;
        ./create_new_optimization.py --name test_dummy_ax --from dummy_ax --machine local --n_sim_workers 2;
        cd test_dummy_ax; python run_example.py --comms local --nworkers 3
    - shell: bash -l {0}
      name: test dummy_mt example
      run: |
        cd optimization_folder;
        ./create_new_optimization.py --name test_dummy_mt --from dummy_mt --machine local --n_sim_workers 2;
        cd test_dummy_mt; python run_example.py --comms local --nworkers 3
